const AUTH_GITHUB_REQUESTED = 'ACTIONS/AUTH_GITHUB_REQUESTED';
const AUTH_GITHUB_SUCCED = 'ACTIONS/AUTH_GITHUB_SUCCED';
const AUTH_GITHUB_FAILED = 'ACTIONS/AUTH_GITHUB_FAILED';
const AUTH_GITHUB_LOGOUT = 'ACTIONS/AUTH_GITHUB_LOGOUT';
export {
  AUTH_GITHUB_REQUESTED,
  AUTH_GITHUB_SUCCED,
  AUTH_GITHUB_FAILED,
  AUTH_GITHUB_LOGOUT,
};
