// flow-typed signature: a1464cd791942c6638a9bc5bb490b49f
// flow-typed version: <<STUB>>/rn-sliding-up-panel_v^1.2.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rn-sliding-up-panel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rn-sliding-up-panel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rn-sliding-up-panel/libs/FlickAnimation' {
  declare module.exports: any;
}

declare module 'rn-sliding-up-panel/libs/layout' {
  declare module.exports: any;
}

declare module 'rn-sliding-up-panel/libs/styles' {
  declare module.exports: any;
}

declare module 'rn-sliding-up-panel/SlidingUpPanel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rn-sliding-up-panel/libs/FlickAnimation.js' {
  declare module.exports: $Exports<'rn-sliding-up-panel/libs/FlickAnimation'>;
}
declare module 'rn-sliding-up-panel/libs/layout.js' {
  declare module.exports: $Exports<'rn-sliding-up-panel/libs/layout'>;
}
declare module 'rn-sliding-up-panel/libs/styles.js' {
  declare module.exports: $Exports<'rn-sliding-up-panel/libs/styles'>;
}
declare module 'rn-sliding-up-panel/SlidingUpPanel.js' {
  declare module.exports: $Exports<'rn-sliding-up-panel/SlidingUpPanel'>;
}
