// @flow

// Please keep this sorted out
const BACKDROP_TRANSPARENT = 'rgba(51, 51, 51, 0.3)';
const BLACK = '#000000';
const BLUE_CYAN = '#72BFDB';
const BORDER_GREY = '#E6E9EE';
const DARK_CYAN = '#68C2C3';
const DARK_GREY = '#909AA3';
const FACEBOOK_BLUE = '#2C407B';
const GOOGLE_RED = '#D25436';
const GREY = '#A5AEB6';
const LIGHT_BLUE = '#4A87F5';
const LIGHT_CYAN = '#ECFAFB';
const LIGHT_GREEN = '#48C5C3';
const LIGHT_GREY = '#E1E4EC';
const LIGHT_GREY_BLUE = '#FAFBFD';
const LIGHT_ORANGE = '#FAEEDF';
const LIGHT_RED = '#ED6162';
const LIGHTER_GREY = '#E6E9EE';
const LIGHTEST_GREY = '#F7F7FA';
const LIGHTEST_RED = '#FDF3F3';
const MAIN_COLOR = '#0C2C5E';
const ORANGE = '#E8AE5F';
const RED = '#EB352C';
const TRANSPARENT = '#0000';
const WHITE = '#FFFFFF';

export {
  BACKDROP_TRANSPARENT,
  BLACK,
  BLUE_CYAN,
  BORDER_GREY,
  DARK_CYAN,
  DARK_GREY,
  FACEBOOK_BLUE,
  GOOGLE_RED,
  GREY as TEXT_GREY,
  GREY,
  LIGHT_BLUE,
  LIGHT_CYAN,
  LIGHT_GREEN,
  LIGHT_GREY,
  LIGHT_GREY_BLUE,
  LIGHT_ORANGE,
  LIGHT_RED,
  LIGHTER_GREY,
  LIGHTEST_GREY,
  LIGHTEST_RED,
  MAIN_COLOR as TEXT_MAIN,
  MAIN_COLOR,
  ORANGE,
  RED,
  TRANSPARENT,
  WHITE,
};
